Fix error when unindent_auto_doc_script is not found
As previously coded, this emits the delightfully cryptic error message

  File "/home/runner/work/stout/stout/./dev-tools/README.md", line 3
    Collection of developer scripts, files, etc, for improving the developer process.
               ^^
  SyntaxError: invalid syntax

Because the failure to find the unindent script results in trying to run
`python README.md`